In [1]:
# ’’’
# export LD_LIBRARY_PATH =/usr/local/lib
# ’’’
import pybgpstream
import pprint
import numpy as np
# Es necesario definir un lapso de tiempo en el cual se observa la RIB.
# Para que la RIB sea consistente el lapso no debe ser muy prolongado.
time_init = "2017-03-01"
time_end = "2017-03-01 00:01"
# Definino el colector desde el cual se obtiene la RIB
# La lista completa esta disponible en https://bgpstream.caida.org/data
collector = 'route-views.saopaulo'
# Defino el target AS , en este caso es la UBA ( AS3449 )
# Los numeros de ASes ( ASN ) estan disponibles en https://bgp.he.net
target_as = 3449
# Genero la consulta a la API
stream = pybgpstream.BGPStream (
from_time = time_init ,
until_time = time_end ,
filter = "type  ribs  and  collector  %s  and  path  %s" % (collector ,target_as))
# Itero en cada uno de los anuncios
for elem in stream :
# Filtro solo los AS - PATHS que tengan como destino
# ( ultimo AS en la cadena ) a la UBA
    if int ( elem.fields [ "as-path" ].split (' ')[ -1]) == target_as :
        pprint.pprint ( elem.fields )

{'as-path': '262757 4230 28513 11664 11664 3449 3449 3449',
 'communities': {'4230:1'},
 'next-hop': '187.16.223.117',
 'prefix': '157.92.0.0/16'}
{'as-path': '52888 1916 27750 3597 3449',
 'communities': set(),
 'next-hop': '187.16.218.21',
 'prefix': '157.92.0.0/16'}
{'as-path': '264268 28329 6762 701 19037 11664 3449 3449 3449',
 'communities': {'28329:1000',
                 '28329:1310',
                 '3000:3000',
                 '3000:3001',
                 '6762:10150',
                 '6762:31'},
 'next-hop': '187.16.221.68',
 'prefix': '157.92.0.0/16'}
{'as-path': '1916 27750 3597 3449',
 'communities': {'1916:400', '1916:10411', '1916:11'},
 'next-hop': '187.16.216.4',
 'prefix': '157.92.0.0/16'}
{'as-path': '262750 28329 6762 701 19037 11664 3449 3449 3449',
 'communities': {'23456:21'},
 'next-hop': '187.16.217.14',
 'prefix': '157.92.0.0/16'}
{'as-path': '28138 16735 12956 701 19037 11664 3449 3449 3449',
 'communities': set(),
 'next-hop': '187.16.216.90',
 'prefix'

In [2]:
'''
IMPORTANT: Load first
export LD_LIBRARY_PATH=/usr/local/lib
'''

#---------------------------------------------------------
# Definiciones


TIME_INIT="2017-03-01"
TIME_END="2017-03-01 00:05"
COLLECTOR='route-views.sg'
targetAS=3449

#---------------------------------------------------------

# Configuracion de la consulta

stream = pybgpstream.BGPStream(
        from_time=TIME_INIT,
        until_time=TIME_END,
        filter="type ribs and collector %s and path %s"%(COLLECTOR,targetAS))

#---------------------------------------------------------

# Ejecucion y parseo de la consulta

# Este loop puede tardar mucho porque la RIB que estamos mirando es sumamente grande

ASPATHS_v=[]   
for elem in stream:
    #print elem.fields.keys()
    #['communities', 'next-hop', 'prefix', 'as-path']
    if targetAS in np.array(elem.fields["as-path"].split(' ')).astype(int):
        ASPATHS_v.append(np.array(elem.fields["as-path"].split(' ')).astype(int))
        
#---------------------------------------------------------

# OUTPUT: AS proveedores de Internet de la UBA (AS3449) 

for ASPATH in ASPATHS_v:
    TargetPosition=np.where(ASPATH==targetAS)[0]
    print(ASPATH[TargetPosition-1])

[11664  3449  3449]
[11664  3449  3449]
[11664  3449  3449]
[11664  3449  3449]


In [3]:
#---------------------------------------------------------
# Definiciones


TIME_INIT="2017-03-01"
TIME_END="2017-03-01 00:05"
COLLECTOR='route-views.sg'
targetAS=3

#---------------------------------------------------------

# Configuracion de la consulta

stream = pybgpstream.BGPStream(
        from_time=TIME_INIT,
        until_time=TIME_END,
        filter="type ribs and collector %s and path %s"%(COLLECTOR,targetAS))

#---------------------------------------------------------

# Ejecucion y parseo de la consulta

# Este loop puede tardar mucho porque la RIB que estamos mirando es sumamente grande

ASPATHS_v=[]
prefix_set=set()  
for elem in stream:
    #print elem.fields.keys()
    #['communities', 'next-hop', 'prefix', 'as-path']
    if str(targetAS) in elem.fields["as-path"].split(' '):
        try:
            ASPATHS_v.append(np.array(elem.fields["as-path"].split(' ')).astype(int))
        except:
            print("Strange element in AS-PATH") 
        try:
            ASPATHS_v.set(elem.fields["prefix"])
        except:
            print("Strange prefix")
        
#---------------------------------------------------------

# OUTPUT: AS proveedores de Internet del MIT (AS3)

# Como tiene muchos PATHS, lo hago mas prolijo que el ejemplo anterior

UpstreamProvider_set=set()
for ASPATH in ASPATHS_v:
    TargetPosition=np.where(ASPATH==targetAS)[0]
    UpstreamProvider_set.add(ASPATH[TargetPosition-1][0])


for UpstreamProvider in UpstreamProvider_set:
    print(UpstreamProvider)

Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange pr

Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange prefix
Strange pr

In [4]:

#---------------------------------------------------------
# Definiciones


TIME_INIT="2017-03-01"
TIME_END="2017-03-01 00:05"
COLLECTOR='route-views.sg'
targetprefix='24.232.0.0/16'

#---------------------------------------------------------

# Configuracion de la consulta

# En este ejemplo se busca un prefijo determinado

stream = pybgpstream.BGPStream(
        from_time=TIME_INIT,
        until_time=TIME_END,
        filter="type ribs and collector %s and prefix %s"%(COLLECTOR,targetprefix))

#---------------------------------------------------------

# Ejecucion y parseo de la consulta

# Este loop puede tardar mucho porque la RIB que estamos mirando es sumamente grande

ASPATHS_set=set()
prefix_set=set()
originAS_set=set()    
for elem in stream:
    #print elem.fields.keys()
    #['communities', 'next-hop', 'prefix', 'as-path']
    #pprint.pprint(elem.fields)
    ASPATHS_set.add(tuple(np.array(elem.fields["as-path"].split(' ')).astype(int).tolist()))
    prefix_set.add(elem.fields["prefix"])
    originAS_set.add(np.array(elem.fields["as-path"].split(' ')).astype(int)[-1])
    
#---------------------------------------------------------

print("---------------------------")
print("AS-PATHS que se observaron hacia el destino\n")
for ASPATH in ASPATHS_set:
    print(ASPATH)
    
#---------------------------------------------------------

print("---------------------------")
print("Prefijos (incluyendo desagregados) que se observaron\n")
for prefix in prefix_set:
    print(prefix)
    
#---------------------------------------------------------
print("---------------------------")
print("AS orginante del prefijo\n") 

for originAS in originAS_set:
    print(originAS)

---------------------------
AS-PATHS que se observaron hacia el destino

(18106, 6453, 3356, 10481, 10318)
(133165, 4637, 3356, 10481, 10318)
(18106, 4657, 6762, 10481)
(24482, 2914, 6762, 10481, 10318)
(24482, 6453, 3356, 10481, 10318)
(38880, 3491, 3549, 10481, 10318)
(6762, 10481, 10318)
(133165, 4637, 6762, 10481, 10318)
(38880, 3491, 6762, 10481, 10318)
---------------------------
Prefijos (incluyendo desagregados) que se observaron

24.232.224.0/20
24.232.160.0/19
24.232.224.0/19
24.232.96.0/19
24.232.192.0/19
24.232.0.0/16
24.232.144.0/20
24.232.128.0/19
24.232.64.0/19
24.232.64.0/20
24.232.0.0/19
24.232.32.0/19
24.232.192.0/20
24.232.128.0/20
24.232.112.0/20
24.232.32.0/20
24.232.16.0/20
24.232.208.0/20
24.232.160.0/20
24.232.80.0/20
24.232.0.0/20
24.232.48.0/20
24.232.240.0/20
24.232.176.0/20
24.232.96.0/20
---------------------------
AS orginante del prefijo

10481
10318
